### ISSUE TITLE
Path option not working.

### ISSUE THREAD

**Issue by nobicycle** [popeye123/ytcc#2]
Hi Wolfgang
Thank you very much for  ytcc.
This syntax does not work (but it used to work):

> ytcc --path Path  --download n --channel-filter channel

Whatever the Path value, the download starts in my default download directory (XFCE , ~/Downloads)
Ditto for the -p option 

> $ ytcc -v
> ytcc version 1.4.0

Best wishes

**Comment by popeye123** [comment]
Thanks for reporting this bug! I found the problem. The commandline parameter `--path` has no effect, if the download path is set in the config (which became default in 1.4.0).
